# Generated by Django 4.1.1 on 2022-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False)),
                ('passageID', models.IntegerField()),
                ('question_type', models.IntegerField()),
                ('question', models.TextField(max_length=1000)),
                ('new_passage', models.TextField(max_length=2000)),
                ('answer', models.TextField(max_length=100)),
                ('d1', models.TextField(max_length=100)),
                ('d2', models.TextField(max_length=100)),
                ('d3', models.TextField(max_length=100)),
                ('d4', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
