# Generated by Django 4.1.1 on 2022-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passageID', models.IntegerField(auto_created=True)),
                ('passage', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'passage',
            },
        ),
    ]
